name: PR Dummy Pipeline

on:
  pull_request:
  

env:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  # Force nox to produce colorful logs:
  FORCE_COLOR: "true"

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: /usr/bin/true
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: /usr/bin/true
  Docs:
    runs-on: ubuntu-latest
    steps:
      - run: /usr/bin/true
